install.packages(c("tidyverse", "caret", "rpart", "rpart.plot", "randomForest", "arules", "arulesViz", "cluster"))
library(tidyverse)
library(caret)
library(rpart)
library(rpart.plot)
library(randomForest)
library(arules)
library(arulesViz)
library(cluster)